import { Inter as FontSans } from "next/font/google";
// import "@/styles/globals.css";
import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";

import { DeepgramContextProvider } from "./context/Deepgram";
import { MessageMetadataContextProvider } from "./context/MessageMetadata";
import { MicrophoneContextProvider } from "./context/Microphone";
import { AudioStoreContextProvider } from "./context/AudioStore";
import { ToastContextProvider } from "./context/Toast";
import { NowPlayingContextProvider } from "react-nowplaying";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ToastContextProvider>
          <MicrophoneContextProvider>
            <AudioStoreContextProvider>
              <NowPlayingContextProvider>
                <MessageMetadataContextProvider>
                  <DeepgramContextProvider>{children}</DeepgramContextProvider>
                </MessageMetadataContextProvider>
              </NowPlayingContextProvider>
            </AudioStoreContextProvider>
          </MicrophoneContextProvider>
        </ToastContextProvider>
      </body>
    </html>
  );
}
